name: publish docker to ECR
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build enricher
        run: sbt clean compile assembly

      - name: Build image
        env:
          REGISTRY: 227470386831.dkr.ecr.eu-central-1.amazonaws.com
          REPOSITORY: enricher-prod
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$(date '+%Y-%m-%d') \
                       -f docker/spark/Dockerfile-enricher \
                      .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        env:
          REGISTRY: 227470386831.dkr.ecr.eu-central-1.amazonaws.com
        run: aws ecr get-login-password | docker login --username AWS --password-stdin $REGISTRY

      - name: Publish image
        env:
          REGISTRY: 227470386831.dkr.ecr.eu-central-1.amazonaws.com
          REPOSITORY: enricher-prod
        run: docker push $REGISTRY/$REPOSITORY:$(date '+%Y-%m-%d')